[workspace]
authors = ["Vansh Nawander <vanshnawander@gmail.com>"]
channels = ["conda-forge","nvidia"]
name = "cuda-sessions"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
cuda-nvcc = "*" 
triton = ">=3.6.0,<4"
pytorch = ">=2.10.0,<3"
matplotlib = ">=3.10.8,<4"
pandas = ">=3.0.0,<4"


[system-requirements]
cuda = "13.0"
